gg_rct_regionArena = nil
gg_rct_baseRed = nil
gg_rct_baseBlue = nil
gg_rct_baseTeal = nil
gg_rct_basePurple = nil
gg_rct_baseYellow = nil
gg_rct_baseOrange = nil
gg_rct_baseGreen = nil
gg_rct_basePink = nil
gg_rct_baseGrey = nil
gg_rct_baseLightBlue = nil
gg_rct_baseDarkGreen = nil
gg_rct_baseBrown = nil
gg_rct_arenaRed = nil
gg_rct_arenaBlue = nil
gg_rct_arenaTeal = nil
gg_rct_arenaPurple = nil
gg_rct_arenaYellow = nil
gg_rct_arenaOrange = nil
gg_rct_arenaGreen = nil
gg_rct_arenaPink = nil
gg_rct_arenaGrey = nil
gg_rct_arenaLightBlue = nil
gg_rct_arenaDarkGreen = nil
gg_rct_arenaBrown = nil
gg_rct_regionArenaVisibility = nil
gg_cam_Victory_cam = nil
function InitGlobals()
end

function CreateRegions()
    local we
    gg_rct_regionArena = Rect(-4736.0, -4736.0, 4864.0, 4736.0)
    gg_rct_baseRed = Rect(-7424.0, 5632.0, -5376.0, 7680.0)
    gg_rct_baseBlue = Rect(-3456.0, 5632.0, -1408.0, 7680.0)
    gg_rct_baseTeal = Rect(1408.0, 5632.0, 3456.0, 7680.0)
    gg_rct_basePurple = Rect(5376.0, 5632.0, 7424.0, 7680.0)
    gg_rct_baseYellow = Rect(5504.0, 1408.0, 7552.0, 3456.0)
    gg_rct_baseOrange = Rect(5504.0, -3456.0, 7552.0, -1408.0)
    gg_rct_baseGreen = Rect(5376.0, -7680.0, 7424.0, -5632.0)
    gg_rct_basePink = Rect(1408.0, -7680.0, 3456.0, -5632.0)
    gg_rct_baseGrey = Rect(-3456.0, -7680.0, -1408.0, -5632.0)
    gg_rct_baseLightBlue = Rect(-7424.0, -7680.0, -5376.0, -5632.0)
    gg_rct_baseDarkGreen = Rect(-7424.0, -3456.0, -5376.0, -1408.0)
    gg_rct_baseBrown = Rect(-7424.0, 1408.0, -5376.0, 3456.0)
    gg_rct_arenaRed = Rect(-640.0, 3328.0, 608.0, 4352.0)
    gg_rct_arenaBlue = Rect(1280.0, 3296.0, 2528.0, 4320.0)
    gg_rct_arenaTeal = Rect(3136.0, 1440.0, 4384.0, 2464.0)
    gg_rct_arenaPurple = Rect(3200.0, -544.0, 4448.0, 480.0)
    gg_rct_arenaYellow = Rect(3136.0, -2432.0, 4384.0, -1408.0)
    gg_rct_arenaOrange = Rect(1312.0, -4352.0, 2560.0, -3328.0)
    gg_rct_arenaGreen = Rect(-608.0, -4352.0, 640.0, -3328.0)
    gg_rct_arenaPink = Rect(-2496.0, -4288.0, -1248.0, -3264.0)
    gg_rct_arenaGrey = Rect(-4384.0, -2432.0, -3136.0, -1408.0)
    gg_rct_arenaLightBlue = Rect(-4448.0, -544.0, -3200.0, 480.0)
    gg_rct_arenaDarkGreen = Rect(-4384.0, 1440.0, -3136.0, 2464.0)
    gg_rct_arenaBrown = Rect(-2496.0, 3264.0, -1248.0, 4288.0)
    gg_rct_regionArenaVisibility = Rect(-3648.0, -3680.0, 3648.0, 3616.0)
end

function CreateCameras()
    gg_cam_Victory_cam = CreateCameraSetup()
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_ROTATION, 90.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_ANGLE_OF_ATTACK, 330.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_TARGET_DISTANCE, 2000.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_ROLL, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_FARZ, 5000.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_NEARZ, 100.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
    CameraSetupSetField(gg_cam_Victory_cam, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
    CameraSetupSetDestPosition(gg_cam_Victory_cam, -27.9, -46.0, 0.0)
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(0), true)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(1), true)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(2), true)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(3), true)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(4), true)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(5), true)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(6), true)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(7), true)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(8), true)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(9), true)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(10), 10)
    ForcePlayerStartLocation(Player(10), 10)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(10), true)
    SetPlayerController(Player(10), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(11), 11)
    ForcePlayerStartLocation(Player(11), 11)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(11), true)
    SetPlayerController(Player(11), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(12), 12)
    ForcePlayerStartLocation(Player(12), 12)
    SetPlayerColor(Player(12), ConvertPlayerColor(12))
    SetPlayerRacePreference(Player(12), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(12), false)
    SetPlayerController(Player(12), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(13), 13)
    ForcePlayerStartLocation(Player(13), 13)
    SetPlayerColor(Player(13), ConvertPlayerColor(13))
    SetPlayerRacePreference(Player(13), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(13), false)
    SetPlayerController(Player(13), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(14), 14)
    ForcePlayerStartLocation(Player(14), 14)
    SetPlayerColor(Player(14), ConvertPlayerColor(14))
    SetPlayerRacePreference(Player(14), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(14), false)
    SetPlayerController(Player(14), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(15), 15)
    ForcePlayerStartLocation(Player(15), 15)
    SetPlayerColor(Player(15), ConvertPlayerColor(15))
    SetPlayerRacePreference(Player(15), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(15), false)
    SetPlayerController(Player(15), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(16), 16)
    ForcePlayerStartLocation(Player(16), 16)
    SetPlayerColor(Player(16), ConvertPlayerColor(16))
    SetPlayerRacePreference(Player(16), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(16), false)
    SetPlayerController(Player(16), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(17), 17)
    ForcePlayerStartLocation(Player(17), 17)
    SetPlayerColor(Player(17), ConvertPlayerColor(17))
    SetPlayerRacePreference(Player(17), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(17), false)
    SetPlayerController(Player(17), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(18), 18)
    ForcePlayerStartLocation(Player(18), 18)
    SetPlayerColor(Player(18), ConvertPlayerColor(18))
    SetPlayerRacePreference(Player(18), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(18), false)
    SetPlayerController(Player(18), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(19), 19)
    ForcePlayerStartLocation(Player(19), 19)
    SetPlayerColor(Player(19), ConvertPlayerColor(19))
    SetPlayerRacePreference(Player(19), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(19), false)
    SetPlayerController(Player(19), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(20), 20)
    ForcePlayerStartLocation(Player(20), 20)
    SetPlayerColor(Player(20), ConvertPlayerColor(20))
    SetPlayerRacePreference(Player(20), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(20), false)
    SetPlayerController(Player(20), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(21), 21)
    ForcePlayerStartLocation(Player(21), 21)
    SetPlayerColor(Player(21), ConvertPlayerColor(21))
    SetPlayerRacePreference(Player(21), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(21), false)
    SetPlayerController(Player(21), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(22), 22)
    ForcePlayerStartLocation(Player(22), 22)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(22), false)
    SetPlayerController(Player(22), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(23), 23)
    ForcePlayerStartLocation(Player(23), 23)
    SetPlayerColor(Player(23), ConvertPlayerColor(23))
    SetPlayerRacePreference(Player(23), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(23), false)
    SetPlayerController(Player(23), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerTeam(Player(1), 0)
    SetPlayerTeam(Player(2), 0)
    SetPlayerTeam(Player(3), 0)
    SetPlayerTeam(Player(4), 0)
    SetPlayerTeam(Player(5), 0)
    SetPlayerTeam(Player(6), 0)
    SetPlayerTeam(Player(7), 0)
    SetPlayerTeam(Player(8), 0)
    SetPlayerTeam(Player(9), 0)
    SetPlayerTeam(Player(10), 0)
    SetPlayerTeam(Player(11), 0)
    SetPlayerTeam(Player(12), 0)
    SetPlayerTeam(Player(13), 0)
    SetPlayerTeam(Player(14), 0)
    SetPlayerTeam(Player(15), 0)
    SetPlayerTeam(Player(16), 0)
    SetPlayerTeam(Player(17), 0)
    SetPlayerTeam(Player(18), 0)
    SetPlayerTeam(Player(19), 0)
    SetPlayerTeam(Player(20), 0)
    SetPlayerTeam(Player(21), 0)
    SetPlayerTeam(Player(22), 0)
    SetPlayerTeam(Player(23), 0)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 2)
    SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 1, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 3)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(2, 3)
    SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 2, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(3, 2)
    SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 3)
    SetStartLocPrio(4, 0, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 1, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 2, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 3)
    SetStartLocPrio(5, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 1, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 2, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(6, 2)
    SetStartLocPrio(6, 0, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 1, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 3)
    SetStartLocPrio(7, 0, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(7, 1, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 2, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 3)
    SetStartLocPrio(8, 0, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 1, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 2, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(9, 2)
    SetStartLocPrio(9, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 1, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(10, 3)
    SetStartLocPrio(10, 0, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 1, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 2, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(11, 3)
    SetStartLocPrio(11, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 2, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(12, 4)
    SetStartLocPrio(12, 0, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 1, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 2, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 3, 23, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(12, 4)
    SetEnemyStartLocPrio(12, 0, 18, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 1, 20, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 2, 22, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 3, 23, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(13, 4)
    SetStartLocPrio(13, 0, 18, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 1, 20, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 2, 22, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 3, 23, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(13, 6)
    SetEnemyStartLocPrio(13, 0, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 1, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 2, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 3, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 4, 9, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 5, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(14, 4)
    SetStartLocPrio(14, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(14, 1, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(14, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(14, 3, 9, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(14, 1)
    SetEnemyStartLocPrio(14, 0, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(15, 2)
    SetStartLocPrio(15, 0, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(15, 1, 22, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(15, 4)
    SetEnemyStartLocPrio(15, 0, 18, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(15, 1, 20, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(15, 2, 22, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(15, 3, 23, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(16, 4)
    SetStartLocPrio(16, 0, 19, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(16, 1, 20, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(16, 2, 22, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(16, 3, 23, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(16, 4)
    SetEnemyStartLocPrio(16, 0, 19, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(16, 1, 20, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(16, 2, 22, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(16, 3, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(17, 5)
    SetStartLocPrio(17, 0, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 1, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 2, 20, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(17, 3, 22, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(17, 4, 23, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(17, 3)
    SetEnemyStartLocPrio(17, 0, 19, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(17, 1, 20, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(17, 2, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(18, 2)
    SetStartLocPrio(18, 0, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 1, 22, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(18, 3)
    SetEnemyStartLocPrio(18, 0, 20, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(18, 1, 22, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(18, 2, 23, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(19, 1)
    SetEnemyStartLocPrio(19, 0, 23, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(20, 1)
    SetStartLocPrio(20, 0, 23, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(20, 1)
    SetEnemyStartLocPrio(20, 0, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(21, 1)
    SetStartLocPrio(21, 0, 23, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(21, 3)
    SetEnemyStartLocPrio(21, 0, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(21, 1, 10, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(21, 2, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(22, 9)
    SetStartLocPrio(22, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 1, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 2, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 3, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 4, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 5, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 6, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 7, 23, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(22, 21)
    SetEnemyStartLocPrio(22, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 2, 2, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 3, 3, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 4, 4, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 5, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 6, 6, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 7, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 8, 8, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 9, 9, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 10, 10, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 11, 11, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 12, 12, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 13, 13, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(22, 14, 14, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 15, 15, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 16, 17, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 17, 20, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 18, 21, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(22, 19, 23, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(23, 16)
    SetStartLocPrio(23, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 2, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 3, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 4, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 5, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 6, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 7, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 8, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 9, 9, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 10, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 11, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 12, 12, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 13, 13, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 14, 14, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(23, 15, 15, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(23, 19)
    SetEnemyStartLocPrio(23, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 2, 2, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(23, 3, 3, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 4, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 5, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 6, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 7, 8, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(23, 8, 10, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 9, 11, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 10, 13, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(23, 11, 14, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 12, 15, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(23, 13, 16, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 14, 17, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 15, 18, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(23, 16, 19, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(23, 17, 21, MAP_LOC_PRIO_HIGH)
end

function main()
    SetCameraBounds(-8192.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -8192.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 8192.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 8192.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -8192.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 8192.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 8192.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -8192.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    SetTerrainFogEx(0, 100000.0, 100000.0, 0.500, 0.000, 0.000, 0.000)
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    CreateCameras()
    InitBlizzard()
    InitGlobals()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("")
    SetPlayers(24)
    SetTeams(24)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, -6400.0, 6592.0)
    DefineStartLocation(1, -2432.0, 6592.0)
    DefineStartLocation(2, 2432.0, 6592.0)
    DefineStartLocation(3, 6400.0, 6592.0)
    DefineStartLocation(4, 6528.0, 2368.0)
    DefineStartLocation(5, 6528.0, -2496.0)
    DefineStartLocation(6, 6400.0, -6720.0)
    DefineStartLocation(7, 2432.0, -6656.0)
    DefineStartLocation(8, -2432.0, -6656.0)
    DefineStartLocation(9, -6400.0, -6656.0)
    DefineStartLocation(10, -6400.0, -2432.0)
    DefineStartLocation(11, -6400.0, 2432.0)
    DefineStartLocation(12, 0.0, -64.0)
    DefineStartLocation(13, 0.0, -64.0)
    DefineStartLocation(14, 0.0, -64.0)
    DefineStartLocation(15, 0.0, -64.0)
    DefineStartLocation(16, 0.0, -64.0)
    DefineStartLocation(17, 0.0, -64.0)
    DefineStartLocation(18, 0.0, -64.0)
    DefineStartLocation(19, 0.0, -64.0)
    DefineStartLocation(20, 0.0, -64.0)
    DefineStartLocation(21, 0.0, -64.0)
    DefineStartLocation(22, 0.0, -64.0)
    DefineStartLocation(23, 0.0, -64.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

